### ISSUE TITLE
Binaries committed by mistake?

### ISSUE THREAD

**Issue by alban** [rkt/stage1-xen#2]
`kernel/initrd` is a binary file that seems to have been committed by mistake. It does not seem to be useful because there is a script `kernel/make-initrd` that rebuild the initrd.

Could it be removed from the repository?

/cc @sstabellini

**Comment by sstabellini** [comment]
On Thu, 21 Jun 2018, Alban Crequy wrote:
> kernel/initrd is a binary file that seems to have been committed by mistake. It does not seem to be useful because there is a
> script kernel/make-initrd that rebuild the initrd.
> 
> Could it be removed from the repository?

Yes, you are right. I removed it.

Thank you.

- Stefano

**Comment by lucab** [comment]
Closed via https://github.com/rkt/stage1-xen/commit/484b17344359b7876cafb29bfce7b09030cc72df
